FROM python:3.11-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir mlflow==3.8.1

EXPOSE 5000

CMD ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:////mlflow/mlflow.db"]
